### ISSUE TITLE
Kann die Thermostate nicht einrichten

### ISSUE THREAD

**Issue by HKoitzsch** [rikroe/cometblue-custom-component#6]
![Screenshot_20241208-094147](https://github.com/user-attachments/assets/993692e5-20df-4f6b-b330-780649d37da0)

Bekomme diese Fehlermeldung. Habe leider wenig Ahnung und daher hoffe ich , dass jemand mir bei diesem Problem helfen kann. 

Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 09:39:24 (4 Vorkommnisse)
Zuletzt protokolliert: 09:41:10

Error setting up entry Comet Blue 88:4A:EA:3B:FC:B3 for eurotronic_cometblue
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 214, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/dbus_fast/aio/message_bus.py", line 385, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eurotronic_cometblue/__init__.py", line 92, in async_setup_entry
    async with cometblue_device:
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/cometblue/__init__.py", line 638, in __aenter__
    await self.connect_async()
  File "/usr/local/lib/python3.13/site-packages/cometblue/__init__.py", line 407, in connect_async
    await self.client.connect()
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 311, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 151, in connect
    async with async_timeout(timeout):
               ~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by rikroe** [comment]
Die Fehlermeldung sagt, dass die Verbindung zu den Thermostaten nicht innerhalb von 20 Sekunden hergestellt werden konnte.
Wie weit sind die Thermostate vom PC mit HA entfernt? Wie wird die Bluetooth-Verbindung hergestellt?
Die besten Erfahrungen wurden mit ESPHome Bluetooth Proxies gemacht, also separaten Geräten, die die Verbindung zwischen HA und den Thermostaten herstellen.

**Comment by HKoitzsch** [comment]
Ich habe mehrere Bluetooth Proxys mit den Shelly Mini laufen sowie eine Bluetooth Adapter. Beim Einrichten werden auch sofort die beiden Thermostate angezeigt. Ich hatte es auch in der Vergangenheit geschafft es einzurichten, nun habe ich aber diese Fehlermeldung. Auch habe ich die Integration deinstalliert und wieder neu installiert. Hat leider auch nichts gebracht.

**Comment by rikroe** [comment]
Schon mal probiert die Bluetooth proxies neu zu starten?

Wenn es mal geklappt hat, wüsste ich auch Anhieb leider nicht weiter (außer das es vielleicht eine Änderung im HA bluetooth Stack gab),die hier Auswirkungen hat.

Meine Thermostate funktionieren mit der aktuellsten Version ohne Probleme.

**Comment by DerGary** [comment]
hast du mal versucht die Timeout zeit zu erhöhen? Dazu einfach auf die drei Punkte des Eintrags klicken und Neu Konfigurieren auswählen, dort kann man den Timeout auf 60 Sekunden erhöhen, das ist bei mir nötig damit es zuverlässig funktioniert.

![image](https://github.com/user-attachments/assets/2609abdb-de09-42e0-afaa-8295e292630d)

**Comment by rikroe** [comment]
Falls noch aktuell: Bitte nochmal mit der neusten Version des Custom Components (20250907.2) testen. Das sollte einige Verbesserungen aus dem Home-Assistant-Projekt nutzen und weniger Abbrüche/bessere Konnektivität haben.
